#!/bin/bash

help() {
    echo -e "
    example: $(basename $0) -q 90 -f /photos/output

        -q <84-100>, 设置压缩级别, 默认95
        -s, 设置最小压缩大小 k 级别
        -f, 当前目录以及子目录文件中的图片将会压缩 (当前目录: $(pwd))
    "

    exit
}

#Set Quality level
#Default = 95
#Max = 100
#Min = 84

# 设置 压缩度
QUALITY=95

# 设置 最小压缩文件大小
mineSize=50
realMineSize=$[mineSize*1024]

# 设置 压缩的文件夹
FOLDER=$(pwd)

while getopts "q:s:f:" o; do
    case "${o}" in
        q)
            if [ ${OPTARG} -ge 84 ] && [ ${OPTARG} -le 100 ];
            #if ((${OPTARG} >= 84 && ${OPTARG} <= 100))
            then
                echo
                q=${OPTARG}
                QUALITY=${OPTARG}
                echo "QUALITY = ${OPTARG}"
                echo
            else
                help
            fi
            ;;

        s)
            s=${OPTARG}
            mineSize=${OPTARG}
            realMineSize=$[mineSize*1024]
            echo "最小压缩大小: ${OPTARG} k"
            echo
            ;;

        f)
            f=${OPTARG}
            FOLDER=${OPTARG}
            echo "当前目录 ${OPTARG} 以及子目录文件中的图片将会压缩......"
            echo
            ;;

        *)
            help
            ;;
    esac
done

# 直接输入 guetzling 进行提示用法
if [ -z "${q}" ] && [ -z "${s}" ] && [ -z "${f}" ];
then
    help
fi

IFS=$'\n';

for f in $(find "$FOLDER" -name '*.jpg')
do
    oldSize=`ls -lh $f | awk '{print $5}'`
    oldFilename=`ls -lh $f | awk '{print $9}'`;

    size=`wc -c < $f`

    if [ $size -ge $realMineSize ];
    then
        now_time=`date '+%Y年%m月%d日 %H:%M:%S'`
        echo "$now_time  正在压缩  ---> $oldFilename  $oldSize"

        guetzli --quality "$QUALITY" "$f" "$f"

        newSize=`ls -lh $f | awk '{print $5}'`
        now_time=`date '+%Y年%m月%d日 %H:%M:%S'`
        echo "$now_time  压缩成功! ---> $oldFilename  $newSize"
        echo
    else
        now_time=`date '+%Y年%m月%d日 %H:%M:%S'`
        echo "$now_time  文件小于 $mineSize k, 取消压缩 ---> $oldFilename  $oldSize"
        echo
    fi
done

for f in $(find "$FOLDER" -name '*.jpeg')
do
    oldSize=`ls -lh $f | awk '{print $5}'`
    oldFilename=`ls -lh $f | awk '{print $9}'`;
    size=`wc -c < $f`

    if [ $size -ge $realMineSize ];
    then
        now_time=`date '+%Y年%m月%d日 %H:%M:%S'`
        echo "$now_time  正在压缩  ---> $oldFilename  $oldSize"

        guetzli --quality "$QUALITY" "$f" "$f"

        newSize=`ls -lh $f | awk '{print $5}'`
        now_time=`date '+%Y年%m月%d日 %H:%M:%S'`
        echo "$now_time  压缩成功! ---> $oldFilename  $newSize"
        echo
    else
        now_time=`date '+%Y年%m月%d日 %H:%M:%S'`
        echo "$now_time  文件小于 $mineSize k, 取消压缩 ---> $oldFilename  $oldSize"
        echo
    fi
